server:
  port: 19999
  servlet:
    context-path: /api/devops
spring:
  application:
    name: phoenix-ops
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-flex:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl